In [1]:
a =4

In [2]:
# !pip install numpy

     ---------------------------------------- 0.0/14.8 MB ? eta -:--:--
     ---------------------------------------- 0.0/14.8 MB 1.4 MB/s eta 0:00:11
     --------------------------------------- 0.1/14.8 MB 825.8 kB/s eta 0:00:18
     --------------------------------------- 0.1/14.8 MB 880.9 kB/s eta 0:00:17
     --------------------------------------- 0.1/14.8 MB 853.3 kB/s eta 0:00:18
     --------------------------------------- 0.2/14.8 MB 833.5 kB/s eta 0:00:18
      -------------------------------------- 0.2/14.8 MB 811.5 kB/s eta 0:00:19
      -------------------------------------- 0.3/14.8 MB 999.9 kB/s eta 0:00:15
      --------------------------------------- 0.4/14.8 MB 1.0 MB/s eta 0:00:14
     - -------------------------------------- 0.5/14.8 MB 1.2 MB/s eta 0:00:13
     - -------------------------------------- 0.5/14.8 MB 1.2 MB/s eta 0:00:12
     - -------------------------------------- 0.6/14.8 MB 1.3 MB/s eta 0:00:12
     - -------------------------------------- 0.7/14.


[notice] A new release of pip is available: 23.0.1 -> 23.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

In [4]:
b=np.array([[6,7,2],[2,3,4]])
b

array([[6, 7, 2],
       [2, 3, 4]])

In [5]:
b.shape

(2, 3)

In [6]:
s=np.array([[4,40],[3,34],[2,55]])
s

array([[ 4, 40],
       [ 3, 34],
       [ 2, 55]])

In [7]:
s.shape

(3, 2)

In [8]:
k=np.array([[[4,40],[2,23],[3,33]],[[4,44],[2,20],[3,35]]])
k

array([[[ 4, 40],
        [ 2, 23],
        [ 3, 33]],

       [[ 4, 44],
        [ 2, 20],
        [ 3, 35]]])

In [9]:
k=np.array([[[4,40],[2,23],[3,33]],[[4,44],[2,20],[3,35]],[[4,43],[2,23],[3,32]]])
k

array([[[ 4, 40],
        [ 2, 23],
        [ 3, 33]],

       [[ 4, 44],
        [ 2, 20],
        [ 3, 35]],

       [[ 4, 43],
        [ 2, 23],
        [ 3, 32]]])

In [10]:
k.shape

(3, 3, 2)

In [11]:
sp=np.array([[4,40,2],[3,34,2],[2,55,0],[2,20,9]])
sp


array([[ 4, 40,  2],
       [ 3, 34,  2],
       [ 2, 55,  0],
       [ 2, 20,  9]])

In [12]:
sp[:-1,:]

array([[ 4, 40,  2],
       [ 3, 34,  2],
       [ 2, 55,  0]])

In [13]:
sp[2:]

array([[ 2, 55,  0],
       [ 2, 20,  9]])

In [14]:
m=np.array([[4,40,2],[3,34,2],[2,55,0]])
m

array([[ 4, 40,  2],
       [ 3, 34,  2],
       [ 2, 55,  0]])

In [18]:
m[0:,0:]

array([[ 4, 40,  2],
       [ 3, 34,  2],
       [ 2, 55,  0]])

In [19]:
x=[3,2,1]
x+5

TypeError: can only concatenate list (not "int") to list

In [20]:
y=([1,2],[2,3])
y+5

TypeError: can only concatenate tuple (not "int") to tuple

In [21]:
kp=np.array([[3,8,4],[9,3,5],[11,15,17],[19,31,8]])
kp

array([[ 3,  8,  4],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [23]:
kp[0,:]=[30,40,50]
kp

array([[30, 40, 50],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [25]:
kp[:,1]=[22,34,4,5]
kp

array([[30, 22, 50],
       [ 9, 34,  5],
       [11,  4, 17],
       [19,  5,  8]])

In [26]:
kp[:2,1:]=[[22,22],[21,44]]
kp

array([[30, 22, 22],
       [ 9, 21, 44],
       [11,  4, 17],
       [19,  5,  8]])

In [27]:
np.append(kp,[[1,1,1]],axis=0)

array([[30, 22, 22],
       [ 9, 21, 44],
       [11,  4, 17],
       [19,  5,  8],
       [ 1,  1,  1]])

In [30]:
np.append(kp,[[1],[3],[4],[5]],axis=1)

array([[30, 22, 22,  1],
       [ 9, 21, 44,  3],
       [11,  4, 17,  4],
       [19,  5,  8,  5]])

In [31]:
np.delete(kp,1,0)

array([[30, 22, 22],
       [11,  4, 17],
       [19,  5,  8]])

In [32]:
np.delete(kp,1,1)

array([[30, 22],
       [ 9, 44],
       [11, 17],
       [19,  8]])

In [33]:
np.delete(kp,3,axis=0)

array([[30, 22, 22],
       [ 9, 21, 44],
       [11,  4, 17]])

In [34]:
kp.reshape(6,2)

array([[30, 22],
       [22,  9],
       [21, 44],
       [11,  4],
       [17, 19],
       [ 5,  8]])

In [36]:
a1=np.array([3.4,3,4])
a1

array([3.4, 3. , 4. ])

In [37]:
a1.dtype

dtype('float64')

In [38]:
a1.astype('int16')

array([3, 3, 4], dtype=int16)

In [39]:
a1.astype(int)

array([3, 3, 4])

In [40]:
a1.sum()

10.4

In [ ]:
#np.array()
#np.ones
#np.zeros()
#np.arrange()
#np.linspace()
#np.random.randint(s)

