In [1]:
import numpy as np

In [2]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [3]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [4]:
np.arrange(1,11,1)

AttributeError: module 'numpy' has no attribute 'arrange'

In [5]:
np.arrange(1,11,1)

AttributeError: module 'numpy' has no attribute 'arrange'

In [6]:
np.linspace(1,10,10,dtype=int)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
list(range(1,11,1))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [8]:
np.random.randint(1,6,1)

array([5])

In [9]:
np.random.randint(1,6,[4,3,2])

array([[[5, 2],
        [1, 4],
        [3, 4]],

       [[1, 4],
        [4, 5],
        [2, 4]],

       [[5, 4],
        [1, 5],
        [5, 1]],

       [[3, 5],
        [3, 4],
        [1, 2]]])

In [10]:
np.random.seed(10)
np.random.randint(31,6000,[4,3])

array([[1320, 4654, 1375],
       [3472, 1211, 2040],
       [4860, 1551, 1980],
       [2073, 1063, 1128]])

In [11]:
np.random.rand(3,4)

array([[0.16911084, 0.08833981, 0.68535982, 0.95339335],
       [0.00394827, 0.51219226, 0.81262096, 0.61252607],
       [0.72175532, 0.29187607, 0.91777412, 0.71457578]])

In [12]:
r=np.loadtxt('somedata.txt',dtype=str)
r

array(['some', 'data', 'outside'], dtype='<U7')

In [13]:
r=np.loadtxt('moredata.txt')
r

array([[12., 45., 67., 77.],
       [25., 66., 43., 66.]])

In [14]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [15]:
p=np.random.rand(3,4)

In [16]:
p

array([[0.54254437, 0.14217005, 0.37334076, 0.67413362],
       [0.44183317, 0.43401399, 0.61776698, 0.51313824],
       [0.65039718, 0.60103895, 0.8052232 , 0.52164715]])

In [17]:
np.savetxt('new.txt',p,delimiter=' ')

In [18]:
np.savetxt('new.txt',p,delimiter=',')